spring:
  datasource:
#    mysql
#    url: jdbc:mysql://localhost:3306/todolist
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  h2
#    url: jdbc:h2:mem:testdb
#    username: sa
#    sql-script-encoding: UTF-8

  h2: #H2 콘솔 활성화
    console:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
#    defer-datasource-initialization: true  테이블 생성 후에 data.sql 실행
jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}